package test;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.support.ui.Select;



import org.apache.logging.log4j.*;

public class GoogleSearch {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {

	//System.setProperty("webdriver.chrome.driver"
		//	,"C:\\Users\\acer\\Downloads\\chromedriver_win32\\chromedriver.exe");
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
// driver.quit();
}



@Test
public void untitled() {
 // Test name: Untitled
 // Step # | name | target | value
 // 1 | open | / | 
 driver.get("https://www.saucedemo.com/");
 // 2 | setWindowSize | 1024x670 | 
 driver.manage().window().setSize(new Dimension(1024, 670));
 // 3 | type | name=q | hermelin
 driver.findElement(By.name("user-name")).sendKeys("standard_user");
 driver.findElement(By.name("password")).sendKeys("secret_sauce");

 // 4 | sendKeys | name=q | ${KEY_ENTER}
 driver.findElement(By.name("login-button")).sendKeys(Keys.ENTER);
 
 
}


public static void main(String args[]) {
	  JUnitCore junit = new JUnitCore();
	  junit.addListener(new TextListener(System.out));
	  Logger logger=LogManager.getLogger(GoogleSearch.class);
	  org.junit.runner.Result result = junit.run(GoogleSearch.class); // Replace "SampleTest" with the name of your class
	 
		
	  logger.debug("logging");
	 
	  
	  if (result.getFailureCount() > 0) {
	    System.out.println("Test failed.");
	    System.exit(1);
	  } else {
	    System.out.println("Test finished successfully.");
	    System.exit(0);
		
	  }
	}
}